### ISSUE TITLE
either a library or songs of war is causing other mixins from other mods to crash

### ISSUE THREAD

**Issue by Mysticpasta1** [ArkTechMC/SongsOfWar#1]
Time to throw you in the washing machine (as your description stated) XD

Jupiter, Neptune, any mods (like lodestone or wizard's reborn), and Songs Of War 

startup crash with getTooltip mixin of the other mod/s

example mixin crash due to SOW

```Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Variable modifier target for net/minecraft/world/item/ItemStack::wizards_reborn$getTooltip was removed by another injector [INJECT Applicator Phase -> wizards_reborn.mixins.json:ItemStackMixin from mod wizards_reborn -> Apply Injections ->  -> Inject -> wizards_reborn.mixins.json:ItemStackMixin from mod wizards_reborn->@ModifyVariable::wizards_reborn$getTooltip(Lnet/minecraft/world/entity/ai/attributes/AttributeModifier;)Lnet/minecraft/world/entity/ai/attributes/AttributeModifier;]```

**Comment by Mysticpasta1** [comment]
this is forge 1.20.1

**Comment by IAFEnvoy** [comment]
Tested and this is a bug caused by Neptune, not SoW.

I will pass this issue to Neptune's issue tracker

**Comment by Mysticpasta1** [comment]
thanks
