### ISSUE TITLE
DOEN T LOAD

### ISSUE THREAD

**Issue by DarkPuppet74** [ArkTechMC/SongsOfWar#2]
1 SICK MOD 2 if you make forge + neoforge file it doent load for forge. but if is it JUST forge works fine. so maybe or idk how to use that file or just make separete version. like only forge, only neoforge etc

**Comment by IAFEnvoy** [comment]
As NeoForge team said that on 1.20.1 forge and neoforge are same so the mod should be load correctly. Also i have test it works properly.

If you game crash, please send a crash log instead of spam. Please do not spam here or i cannot resolve any problem.
